apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: observer
rules:
- apiGroups: [""]
  resources: ["configmaps", "deployments"]
  verbs: ["get", "list", "watch"]